// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GoProject/main/component"
	"GoProject/main/handler"
	"GoProject/main/mapper"
	"GoProject/main/router"
	"GoProject/main/service"
)

// Injectors from wire.go:

func NewApp() *router.AppRouter {
	engine := component.NewRouter()
	xormEngine := component.NewPostgres()
	userMapper := mapper.NewUserMapper(xormEngine)
	userService := service.NewUserService(userMapper)
	userHandler := handler.NewUserHandler(userService)
	fileMapper := mapper.NewFileMapper(xormEngine)
	fileService := service.NewFileService(fileMapper)
	fileHandler := handler.NewFileHandler(fileService)
	rpcService := service.NewRPCService()
	rpcHandler := handler.NewRPCHandler(rpcService)
	appRouter := &router.AppRouter{
		Engine:  engine,
		UserApi: userHandler,
		FileApi: fileHandler,
		RPCApi:  rpcHandler,
	}
	return appRouter
}
