[database]
dbms = 'postgres'
host = 'localhost'
port = 5432
user = 'postgres'
passwd = 'postgres'
dbname = 'postgres'
params = { sslmode = 'disable' }

#服务器配置
[server]
host = 'localhost'
port = 8088
#用户文件存储目录
savedir = '/www'

[redis]
host = 'localhost'
port = 443
