[database]
dbms = 'postgres'
host = 'localhost'
port = 5432
user = 'postgres'
passwd = 'postgres'
dbname = 'postgres'
params = { sslmode = 'disable' }

[server]
host = 'localhost'
port = 8088
slave = false

[redis]
host = 'localhost'
port = 443
